//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.CUKCUK.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.CUKCUK.Common.Resources.ResourceVN", typeof(ResourceVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa không thành công.
        /// </summary>
        public static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trùng mã món ăn.
        /// </summary>
        public static string DuplicateFoodCode {
            get {
                return ResourceManager.GetString("DuplicateFoodCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trùng mã nhóm thực đơn.
        /// </summary>
        public static string DuplicateFoodGroupCode {
            get {
                return ResourceManager.GetString("DuplicateFoodGroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trùng địa điểm chế biến.
        /// </summary>
        public static string DuplicateProcessedPlace {
            get {
                return ResourceManager.GetString("DuplicateProcessedPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trùng sở thích phục vụ.
        /// </summary>
        public static string DuplicateServiceHobby {
            get {
                return ResourceManager.GetString("DuplicateServiceHobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trùng đơn vị tính.
        /// </summary>
        public static string DuplicateUnitName {
            get {
                return ResourceManager.GetString("DuplicateUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã món ăn không được để trống.
        /// </summary>
        public static string EmptyFoodCode {
            get {
                return ResourceManager.GetString("EmptyFoodCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhóm thực đơn không được để trống.
        /// </summary>
        public static string EmptyFoodGroupCode {
            get {
                return ResourceManager.GetString("EmptyFoodGroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm thực đơn không được để trống.
        /// </summary>
        public static string EmptyFoodGroupName {
            get {
                return ResourceManager.GetString("EmptyFoodGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên món ăn không được để trống.
        /// </summary>
        public static string EmptyFoodName {
            get {
                return ResourceManager.GetString("EmptyFoodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá bán không được để trống.
        /// </summary>
        public static string EmptyFoodPrice {
            get {
                return ResourceManager.GetString("EmptyFoodPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tính không được để trống.
        /// </summary>
        public static string EmptyFoodUnit {
            get {
                return ResourceManager.GetString("EmptyFoodUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa điểm chế biến không được để trống.
        /// </summary>
        public static string EmptyProcessedPlace {
            get {
                return ResourceManager.GetString("EmptyProcessedPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sở thích phục vụ klhông được để trống.
        /// </summary>
        public static string EmptyServiceHobby {
            get {
                return ResourceManager.GetString("EmptyServiceHobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đợn vị tính không được để trống.
        /// </summary>
        public static string EmptyUnitName {
            get {
                return ResourceManager.GetString("EmptyUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liêu đầu vào.
        /// </summary>
        public static string NoInput {
            get {
                return ResourceManager.GetString("NoInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích thước ảnh tải lên qua dung lượng cho phép ( &lt;5Mb).
        /// </summary>
        public static string Oversize {
            get {
                return ResourceManager.GetString("Oversize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi Server.
        /// </summary>
        public static string ServerInternal {
            get {
                return ResourceManager.GetString("ServerInternal", resourceCulture);
            }
        }
    }
}
